#!/bin/bash -l

# Run all system tests, or those explictily specified on the command line

NFAILED=0
EXITONFAIL="TRUE"
SERIALBINARY=../src/dissolve
TESTS=""
NTESTS="0"
COMMONARGS="-x -i"

while getopts "as:p:" op
do
	case $op in
		s)
			SERIALBINARY=${OPTARG}
			echo "Serial binary to use is '${SERIALBINARY}'"
			;;
		\?)
			echo "Error: Unrecognised switch '$op'"
			exit 1
			;;
		*)
			echo "Error: Extra operands given."
			echo "Usage: $0 [-a] [-s <serial binary>] [-p <parallel binary>]"
			exit 1
			;;
	esac
done

# Check binaries
if [ ! -e $SERIALBINARY ]
then
	echo "Couldn't find serial binary, so no serial tests will be performed."
	SERIALBINARY="NO"
	exit 1
fi

# Assemble list of tests supplied, or construct list of all tests
shift $(expr $OPTIND - 1)
while test $# -gt 0
do
	if [ ! -d $1 ]
	then
		echo "Error: No such test '$1' exists, or it is not a directory."
		exit 1
	fi
	TEST[NTESTS]=$1
	((NTESTS++))
	shift
done

if [ "$NTESTS" -eq "0" ]
then
	for test in [a-z]*
	do
		if [ -d $test ]
		then
			TEST[NTESTS]=$test
			((NTESTS++))
		fi
	done
fi
echo "There are $NTESTS tests to run: ${TEST[@]}"

echo ${TEST[0]} | parallel "./go-faster-sub {} $SERIALBINARY"

# Did we have any failures

if [ "$NFAILED" -gt "0" ]
then
	echo -e "\nOne or more tests failed.\n"
	exit 1
fi

exit 0
